Please set FC1_WIDTH!!
Loading /home/felipes/Computational-Intelligence-Lab---ETHZ/road_segmentation/training/images/satImage_001.png
Loading /home/felipes/Computational-Intelligence-Lab---ETHZ/road_segmentation/training/images/satImage_002.png
Loading /home/felipes/Computational-Intelligence-Lab---ETHZ/road_segmentation/training/images/satImage_003.png
Loading /home/felipes/Computational-Intelligence-Lab---ETHZ/road_segmentation/training/images/satImage_004.png
Loading /home/felipes/Computational-Intelligence-Lab---ETHZ/road_segmentation/training/images/satImage_005.png
Loading /home/felipes/Computational-Intelligence-Lab---ETHZ/road_segmentation/training/images/satImage_006.png
Loading /home/felipes/Computational-Intelligence-Lab---ETHZ/road_segmentation/training/images/satImage_007.png
Loading /home/felipes/Computational-Intelligence-Lab---ETHZ/road_segmentation/training/images/satImage_008.png
Loading /home/felipes/Computational-Intelligence-Lab---ETHZ/road_segmentation/training/images/satImage_009.png
Loading /home/felipes/Computational-Intelligence-Lab---ETHZ/road_segmentation/training/images/satImage_010.png
Traceback (most recent call last):
  File "road_segmentation/tf_aerial_images_felipe.py", line 854, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "road_segmentation/tf_aerial_images_felipe.py", line 371, in main
    train_data = extract_data(train_data_filename, TRAINING_SIZE, STARTING_ID, CONTEXT_ADDITIVE_FACTOR)
  File "road_segmentation/tf_aerial_images_felipe.py", line 237, in extract_data
    img_patches = [img_crop_context(imgs[i], IMG_PATCH_SIZE, IMG_PATCH_SIZE,context_factor) for i in range(num_images)]
  File "road_segmentation/tf_aerial_images_felipe.py", line 237, in <listcomp>
    img_patches = [img_crop_context(imgs[i], IMG_PATCH_SIZE, IMG_PATCH_SIZE,context_factor) for i in range(num_images)]
  File "road_segmentation/tf_aerial_images_felipe.py", line 103, in img_crop_context
    plt.title(title)
  File "/home/felipes/.local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 1465, in title
    return gca().set_title(s, *args, **kwargs)
  File "/home/felipes/.local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 950, in gca
    return gcf().gca(**kwargs)
  File "/home/felipes/.local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 586, in gcf
    return figure()
  File "/home/felipes/.local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/home/felipes/.local/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/home/felipes/.local/lib/python3.5/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1871, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
